# Read env file
spring.config.import = optional:file:.env[.properties]

# Server port
server.port=4001

#Configure database access
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/foodstock
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true



# Eureka config
spring.application.name=CITY-SERVICE
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8787/eureka
eureka.instance.hostname=localhost

# Springdoc config
springdoc.version=v1.0
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

#Security Config
keyStore.path=keystore.jks
keyStore.password=password
keyStore.alias=auth-server