apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: prometheus

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: {{ .Values.influxdb.service.type }}
  ports:
    - port: {{ .Values.influxdb.service.port }}
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
    app: influxdb