server:
  port: 5000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:8100"
                allowedHeaders:
                  - "Origin"
                  - "Content-Type"
                  - "Accept"
                  - "Authorization"
                  - "Referer"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
      routes:
        - id: COMMUNITY-SERVICE
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/api/v1/communities/**
        - id: CITY-SERVICE
          uri: lb://CITY-SERVICE
          predicates:
            - Path=/api/v1/cities/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: PRODUCT-TO-COMMUNITY-SERVICE
          uri: lb://PRODUCT-TO-COMMUNITY-SERVICE
          predicates:
            - Path=/api/v1/product-to-community/**
        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/v1/categories/**
        - id: PUBS-SERVICE
          uri: lb://PUBS-SERVICE
          predicates:
            - Path=/api/v1/pubs/**
    discovery:
      locator:
        enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8787/eureka
  instance:
    hostname: localhost