services:
  microservice1:
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - dapr-network

  microservice2:
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - dapr-network

  dapr:
    image: daprio/daprd:latest
    ports:
      - "3500:3500"
    command: ["./daprd", "-app-id", "microservice1", "-app-port", "8080", "-dapr-http-port", "3500"]
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge