name: 'Snyk Test'
description: 'Run Snyk test and log vulnerabilities'
inputs:
  project:
    description: 'Project name'
    required: true
  file:
    description: 'Build file path'
    required: true
  all-sub-projects:
    description: 'Include all sub-projects'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Run Snyk test for ${{ inputs.project }}
      run: snyk test --file=${{ inputs.file }}${{ inputs.all-sub-projects && ' --all-sub-projects' || '' }} || true
      continue-on-error: true
      id: snyk-${{ inputs.project }}

    - name: Log vulnerabilities for ${{ inputs.project }}
      if: always()
      run: snyk test --file=${{ inputs.file }}${{ inputs.all-sub-projects && ' --all-sub-projects' || '' }} > snyk-${{ inputs.project }}.log || true