name: trivy-scan

on:
    push:
        branches:
            - master
            - main
            - devel
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    trivy:
        runs-on: ubuntu-latest
        steps:
            - name: install trivy
              uses: aquasec/trivy 